---
sudo: required
language: python
python: 2.7
services:
  - docker
before_install:
  - sudo apt-get -qq update
install:
  - pip install molecule docker
  # - pip install required driver (e.g. docker, python-vagrant, shade, boto, apache-libcloud)
script:
  - molecule test
notifications:
  slack:
    rooms:
      secure: Ri7SUaX0P6nzV13jemZfQ6ZtbJohPAD3pZk5YvPGBVXgnal1O1asQ4P/7Z1QbIhBy9K99Khg+vH9mTTvRk34zbJ+iFc564dEbF+oQg6gp0WMLlQt7/jRUo/JJIQ/hnLpLX8n8Fe5CaZ1TadMtGrTkKVqrTWQKDiX4uUZ2WgdU5PLZdQKiUpPDBxJCL+bTon0fTKLO4kOdYiYAQ8P+E8FfBWxV2XRVrAA6LATIl7xFNsyag2t5Y5nec3AbjvMJNrVq+DmzLggsb47mBGa2NtBkpfU+bYjBvBLNDIRnkXEQMPU4erkAwghFjt0CrX3BPeiRWGV9W2+vkPv2HOIpPZhEqzfR3TMxU/QQDQa9e2lYbaH/dFL2Y+mSPyPH8rcgbjaSnXbyRvJODQzvqVZ8ULe/rkop5o6OSxFhupHcFUUXExTATu0jESpHgMayCqKvaeOcQyePbWktgEbFXh2FdyQV0DQSGZiQdCSmj58+lFd7HHOApFn5rsDIjW0q/xO0JNGJyOwznXuO5cwcN9tqsiLbLiWPjibgtmzRKs1NKjtgMpW0YjhUfbHn2rGokSsEQvzhk1R8pTh6JNFO8jInvdD+utM2/yDBJCZaIv8MSinEU/rNEavAgDBMWOp0BA6IGeWor9oDSxXhZHwGb0SWEvfWVmEjrSSaDiaEvatSeDSzCA=
